# -*- coding: utf-8 -*-
"""Recuit_Simule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSadhqvjp1-Mw-7wfrx9jshb1lR5mYOh
"""

import time, math, random
from collections import defaultdict
from itertools import combinations

def load_crs(path):
    exams = {}
    with open(path, "r") as f:
        for line in f:
            p = line.strip().split()
            if len(p) == 2:
                exams[int(p[0])] = int(p[1])
    return exams

def load_stu(path):
    students = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                students.append(list(map(int, line.split())))
    return students

def build_conflict_graph(students):
    g = defaultdict(set)
    for exam_list in students:
        for a, b in combinations(exam_list, 2):
            g[a].add(b)
            g[b].add(a)
    return g

def greedy_initial_solution(exams_list, g, max_slots):
    order = sorted(exams_list, key=lambda e: len(g.get(e, set())), reverse=True)
    sol = {}
    for e in order:
        best_slot = 0
        best_conf = None
        for s in range(max_slots):
            conf = 0
            for nb in g.get(e, []):
                if nb in sol and sol[nb] == s:
                    conf += 1
            if best_conf is None or conf < best_conf:
                best_conf = conf
                best_slot = s
                if best_conf == 0:
                    break
        sol[e] = best_slot
    return sol

def init_conflict_counts(exams_list, sol, g):
    cc = {e: 0 for e in exams_list}
    for e in exams_list:
        se = sol[e]
        for nb in g.get(e, []):
            if e < nb and se == sol[nb]:
                cc[e] += 1
                cc[nb] += 1
    return cc

def total_conflicts_from_cc(cc):
    return sum(cc.values()) // 2

def delta_cost_move(sol, g, exam, old_slot, new_slot):
    d = 0
    for nb in g.get(exam, []):
        if sol[nb] == old_slot:
            d -= 1
        if sol[nb] == new_slot:
            d += 1
    return d

def apply_move_update(sol, cc, g, exam, old_slot, new_slot):
    for nb in g.get(exam, []):
        snb = sol[nb]
        if snb == old_slot:
            cc[exam] -= 1
            cc[nb]   -= 1
        if snb == new_slot:
            cc[exam] += 1
            cc[nb]   += 1
    sol[exam] = new_slot

def apply_swap_update(sol, cc, g, a, b):
    sa = sol[a]
    sb = sol[b]
    if sa == sb:
        return 0
    # compute delta as move a to sb and b to sa, but apply carefully
    # easiest: perform two moves with correct updates
    d1 = delta_cost_move(sol, g, a, sa, sb)
    apply_move_update(sol, cc, g, a, sa, sb)
    d2 = delta_cost_move(sol, g, b, sb, sa)
    apply_move_update(sol, cc, g, b, sb, sa)
    return d1 + d2

def simulated_annealing_fast(exams_list, g, max_slots,
                            iters=60000, alpha=0.9995, seed=42,
                            pick_conflicted_prob=0.85,
                            T0=10.0,
                            swap_prob=0.10):
    random.seed(seed)

    sol = greedy_initial_solution(exams_list, g, max_slots)
    cc = init_conflict_counts(exams_list, sol, g)

    cur_cost = total_conflicts_from_cc(cc)
    best_cost = cur_cost
    best_sol = dict(sol)

    conflicted = {e for e in exams_list if cc[e] > 0}
    T = T0

    exams_tuple = tuple(exams_list)

    for _ in range(iters):
        if best_cost == 0:
            break

        use_conf = conflicted and (random.random() < pick_conflicted_prob)

        # Choose move type
        if random.random() < swap_prob and len(exams_tuple) >= 2:
            # SWAP
            if use_conf:
                a = random.choice(tuple(conflicted))
                b = random.choice(exams_tuple)
            else:
                a = random.choice(exams_tuple)
                b = random.choice(exams_tuple)
            if a == b:
                continue

            old_cost = cur_cost
            d = apply_swap_update(sol, cc, g, a, b)
            new_cost = old_cost + d

            # accept
            accept = (d <= 0) or (T > 1e-12 and random.random() < math.exp(-d / T))
            if accept:
                cur_cost = new_cost
                if cur_cost < best_cost:
                    best_cost = cur_cost
                    best_sol = dict(sol)
            else:
                # revert swap by swapping back
                apply_swap_update(sol, cc, g, a, b)  # swap back
                cur_cost = old_cost

            # update conflicted for a,b and neighbors
            for x in (a, b):
                if cc[x] > 0:
                    conflicted.add(x)
                else:
                    conflicted.discard(x)
                for nb in g.get(x, []):
                    if cc[nb] > 0:
                        conflicted.add(nb)
                    else:
                        conflicted.discard(nb)

        else:
            # MOVE
            exam = random.choice(tuple(conflicted)) if use_conf else random.choice(exams_tuple)
            old_slot = sol[exam]
            new_slot = random.randrange(max_slots)
            if new_slot == old_slot:
                continue

            d = delta_cost_move(sol, g, exam, old_slot, new_slot)

            if d <= 0 or (T > 1e-12 and random.random() < math.exp(-d / T)):
                apply_move_update(sol, cc, g, exam, old_slot, new_slot)
                cur_cost += d

                # update conflicted for exam and neighbors
                if cc[exam] > 0:
                    conflicted.add(exam)
                else:
                    conflicted.discard(exam)

                for nb in g.get(exam, []):
                    if cc[nb] > 0:
                        conflicted.add(nb)
                    else:
                        conflicted.discard(nb)

                if cur_cost < best_cost:
                    best_cost = cur_cost
                    best_sol = dict(sol)

        T *= alpha
        if T < 1e-6:
            T = 1e-6

    return best_sol, best_cost

def multi_start_sa(exams_list, g, max_slots, runs=8, iters=60000, base_seed=100):
    best_overall = None
    best_cost = None
    for r in range(runs):
        seed = base_seed + r
        sol, c = simulated_annealing_fast(
            exams_list, g, max_slots,
            iters=iters, alpha=0.9995, seed=seed,
            pick_conflicted_prob=0.85, T0=10.0, swap_prob=0.10
        )
        if best_cost is None or c < best_cost:
            best_cost = c
            best_overall = sol
    return best_overall, best_cost

def run_sta(max_slots):
    DATASET = "sta-f-83"
    exams = load_crs(f"datasets/{DATASET}.crs")
    students = load_stu(f"datasets/{DATASET}.stu")
    g = build_conflict_graph(students)
    exams_list = sorted(exams.keys())

    init_sol = greedy_initial_solution(exams_list, g, max_slots)
    init_cc = init_conflict_counts(exams_list, init_sol, g)
    init_cost = total_conflicts_from_cc(init_cc)

    start = time.time()
    _, best_conf = multi_start_sa(exams_list, g, max_slots, runs=8, iters=60000, base_seed=100)
    elapsed = time.time() - start


    print(f"[RESULT] Algorithm: Recuit Simulé | Time: {elapsed:.1f}s | Conflicts: {best_conf}")

for s in [10]:
    run_sta(s)